const http=require('http');
const fs=require('fs/promises');
const fsSync=require('fs');
const path=require('path');
const crypto=require('crypto');
const ROOT=__dirname;loadEnv(path.join(ROOT,'.env'));
const PORT=Number(process.env.PORT||3000),PUBLIC=path.join(ROOT,'public'),DATA=path.join(ROOT,'data');
const FILES={missions:path.join(DATA,'crm.json'),mail:path.join(DATA,'viral-mail-db.json'),session:path.join(DATA,'user-session.json'),activity:path.join(DATA,'activity.json')};
const MODEL=process.env.OPENAI_MODEL||'gpt-5.5';
const STAGES=['clarifier','relancer','en_cours','bloque','fait'];
const LABEL={clarifier:'A clarifier',relancer:'A relancer',en_cours:'En cours',bloque:'Bloque',fait:'Fait'};
const HINT='Mode local actif : je peux creer, relancer, classer et chiffrer tes missions. Ajoute OPENAI_API_KEY pour le chat libre.';
function loadEnv(file){if(!fsSync.existsSync(file))return;for(const line of fsSync.readFileSync(file,'utf8').split(/\r?\n/)){const m=line.trim().match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);if(!m||line.trim().startsWith('#'))continue;let v=m[2].trim();if((v.startsWith('"')&&v.endsWith('"'))||(v.startsWith("'")&&v.endsWith("'")))v=v.slice(1,-1);if(!process.env[m[1]])process.env[m[1]]=v}}
async function readJson(file,fallback){try{return JSON.parse(await fs.readFile(file,'utf8'))}catch(e){if(e.code==='ENOENT')return typeof fallback==='function'?fallback():fallback;throw e}}
async function writeJson(file,value){await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,JSON.stringify(value,null,2)+'\n')}
function addDays(n){const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
function demoMissions(){const now=new Date().toISOString();return[{id:'demo-street-launch',name:'Lancement street campaign',company:'Kroma Demo',email:'',phone:'',stage:'en_cours',value:2500,nextAction:'Valider le plan de diffusion et les formats prioritaires.',nextActionDate:addDays(6),owner:'Mathis',source:'Demo local',projectType:'Street marketing',sensitivity:'Execution simple, visible, mesurable.',messageDraft:"Je te propose qu'on valide aujourd'hui les formats prioritaires, puis je verrouille le planning.",notes:[{id:'demo-note-1',text:"Transformer l'energie DA en actions claires.",createdAt:now}],createdAt:now,updatedAt:now},{id:'demo-shoot-plan',name:'Tournage capsule brand',company:'Studio Demo',email:'',phone:'',stage:'relancer',value:900,nextAction:'Confirmer le lieu, les participants et la checklist matos.',nextActionDate:addDays(-1),owner:'Mathis',source:'Demo local',projectType:'Tournage',sensitivity:"Cadrer le deroule avant de bloquer l'equipe.",messageDraft:'Je veux verrouiller le lieu, les horaires et la checklist avant le tournage.',notes:[],createdAt:now,updatedAt:now},{id:'demo-brand-pack',name:'Pack DA Kroma',company:'Prospect createur',email:'',phone:'',stage:'clarifier',value:1200,nextAction:'Envoyer une proposition courte avec deux options de budget.',nextActionDate:addDays(2),owner:'Mathis',source:'Demo local',projectType:'Branding',sensitivity:'Offre lisible, impact direct.',messageDraft:"Je t'envoie deux options : une version essentielle et une version complete avec declinaisons social media.",notes:[],createdAt:now,updatedAt:now}]}
function defaultSession(){return{version:1,updatedAt:null,profile:{name:'Mathis',role:'Chef de projet creatif',email:'',avatarText:'MD'},workspace:{name:'Kroma HQ',tagline:'Street x minimal ops',weekLabel:'Semaine active'},preferences:{defaultOwner:'Mathis'}}}
function emptyMail(){return{version:1,updatedAt:null,source:'Gmail missions',processedMessageIds:[],imports:[],tasks:[],shoots:[],weeklyRecaps:[]}}
const readMissions=()=>readJson(FILES.missions,demoMissions);const writeMissions=v=>writeJson(FILES.missions,v);
const readSession=()=>readJson(FILES.session,defaultSession);const writeSession=v=>writeJson(FILES.session,v);
const readMail=()=>readJson(FILES.mail,emptyMail);const writeMail=v=>writeJson(FILES.mail,v);
const readActivity=()=>readJson(FILES.activity,[]);
async function log(label,type='automation'){const a=await readActivity();a.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),type,label});await writeJson(FILES.activity,a.slice(0,200))}
function safe(v,max=500){return String(v??'').trim().slice(0,max)}function num(v){const n=Number(v);return Number.isFinite(n)?n:0}
function sanitizeMission(b,e={}){const now=new Date().toISOString(),stage=STAGES.includes(b.stage)?b.stage:(e.stage||'clarifier');return{id:e.id||b.id||crypto.randomUUID(),name:safe(b.name??e.name,140)||'Mission sans nom',company:safe(b.company??e.company,140),email:safe(b.email??e.email,140),phone:safe(b.phone??e.phone,80),stage,value:num(b.value??e.value),nextAction:safe(b.nextAction??e.nextAction,500),nextActionDate:safe(b.nextActionDate??e.nextActionDate,20),owner:safe(b.owner??e.owner,80)||'Mathis',source:safe(b.source??e.source,140)||'Manuel',projectType:safe(b.projectType??e.projectType,100),sensitivity:safe(b.sensitivity??e.sensitivity,500),messageDraft:safe(b.messageDraft??e.messageDraft,900),notes:Array.isArray(e.notes)?e.notes:[],createdAt:e.createdAt||now,updatedAt:now}}
function sanitizeSession(b,c=defaultSession()){const initials=safe(b.profile?.avatarText)||safe(b.profile?.name||c.profile.name).split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase()||'KH';return{version:1,updatedAt:new Date().toISOString(),profile:{...c.profile,...(b.profile||{}),avatarText:initials},workspace:{...c.workspace,...(b.workspace||{})},preferences:{...c.preferences,...(b.preferences||{})}}}
function days(d){if(!d)return Infinity;const t=new Date(`${d}T00:00:00`),n=new Date();n.setHours(0,0,0,0);return Math.round((t-n)/86400000)}
function stats(missions){const active=missions.filter(m=>m.stage!=='fait'),overdue=active.filter(m=>days(m.nextActionDate)<0),dueSoon=active.filter(m=>days(m.nextActionDate)>=0&&days(m.nextActionDate)<=7);const byStage=STAGES.map(stage=>({stage,label:LABEL[stage],count:missions.filter(m=>m.stage===stage).length,value:missions.filter(m=>m.stage===stage).reduce((s,m)=>s+num(m.value),0)}));const byMonth={};for(const m of missions){const k=(m.updatedAt||new Date().toISOString()).slice(0,7);byMonth[k]??={in_progress:0,won:0};if(m.stage==='fait')byMonth[k].won+=num(m.value);else byMonth[k].in_progress+=num(m.value)}return{total:missions.length,active:active.length,overdue:overdue.length,dueSoon:dueSoon.length,pipelineValue:active.reduce((s,m)=>s+num(m.value),0),wonValue:missions.filter(m=>m.stage==='fait').reduce((s,m)=>s+num(m.value),0),byStage,byMonth}}
function norm(t){return safe(t,500).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}function findMission(missions,t){const n=norm(t);return missions.find(m=>norm(m.id)===n)||missions.find(m=>norm(m.name)===n)||missions.find(m=>norm(m.name).includes(n)||n.includes(norm(m.name)))||missions.find(m=>norm(m.company).includes(n))}
async function localCommand(message,missions){const raw=safe(message,1600),n=norm(raw);let m=raw.match(/^(?:nouvelle mission|cree mission|crée mission|ajoute mission)\s+(.+)$/i);if(m){let name=m[1].trim(),company='';const pm=name.match(/^(.*)\s+pour\s+(.+)$/i);if(pm){name=pm[1].trim();company=pm[2].trim()}const mission=sanitizeMission({name,company,source:'Jarvis'});missions.push(mission);await writeMissions(missions);await log(`Mission creee : ${mission.name}`,'mission_created');return `Mission creee : "${mission.name}"${company?` (${company})`:''}. Stage : a clarifier.`}
m=raw.match(/^relance\s+(.+)$/i);if(m){const x=findMission(missions,m[1]);if(!x)return`Je ne trouve pas "${m[1]}".`;x.stage='relancer';x.updatedAt=new Date().toISOString();await writeMissions(missions);await log(`Relance programmee : ${x.name}`,'mission_relance');return `"${x.name}" passe en a relancer. Message pret a copier :\n\n${x.messageDraft||`Je reviens vers toi sur ${x.name} pour debloquer la suite.`}`}
m=raw.match(/^(?:termine|cloture|fait)\s+(.+)$/i);if(m){const x=findMission(missions,m[1]);if(!x)return`Je ne trouve pas "${m[1]}".`;x.stage='fait';x.updatedAt=new Date().toISOString();await writeMissions(missions);await log(`Mission cloturee : ${x.name}`,'mission_done');return `"${x.name}" est marquee faite. Valeur : ${x.value} EUR.`}
m=raw.match(/^bloque\s+(.+)$/i);if(m){const x=findMission(missions,m[1]);if(!x)return`Je ne trouve pas "${m[1]}".`;x.stage='bloque';x.updatedAt=new Date().toISOString();await writeMissions(missions);await log(`Mission bloquee : ${x.name}`,'mission_blocked');return `"${x.name}" est marquee bloquee.`}
m=raw.match(/^snooze\s+(.+?)\s+(\d+)\s*j/i);if(m){const x=findMission(missions,m[1]);if(!x)return`Je ne trouve pas "${m[1]}".`;x.nextActionDate=addDays(Number(m[2]));x.updatedAt=new Date().toISOString();await writeMissions(missions);await log(`Echeance decalee : ${x.name}`,'mission_snooze');return `Echeance de "${x.name}" decalee au ${x.nextActionDate}.`}
m=raw.match(/^(?:cherche|trouve|recherche)\s+(.+)$/i);if(m){const q=norm(m[1]);const hits=missions.filter(x=>norm(x.name).includes(q)||norm(x.company).includes(q)||norm(x.projectType).includes(q));return hits.length?hits.slice(0,6).map(x=>`- ${x.name} (${LABEL[x.stage]}, echeance ${x.nextActionDate||'non definie'})`).join('\n'):`Aucune mission pour "${m[1]}".`}
if(/^(digest|resume|résumé|point semaine|tempo)$/i.test(n)){const s=stats(missions),late=missions.filter(x=>x.stage!=='fait'&&days(x.nextActionDate)<0),soon=missions.filter(x=>x.stage!=='fait'&&days(x.nextActionDate)>=0&&days(x.nextActionDate)<=7);const lines=[`Radar Kroma : ${s.active} missions actives, ${s.pipelineValue} EUR en pipeline, ${s.wonValue} EUR factures.`,late.length?`En retard : ${late.slice(0,5).map(x=>x.name).join(', ')}.`:'Aucune echeance en retard.',soon.length?`A traiter sous 7 jours : ${soon.slice(0,5).map(x=>x.name).join(', ')}.`:"Rien d'urgent cette semaine."];const db=await readMail();db.weeklyRecaps??=[];db.weeklyRecaps.unshift({id:crypto.randomUUID(),summary:lines.join(' '),importedAt:new Date().toISOString()});await writeMail(db);await log('Digest hebdo genere','digest');return lines.join('\n')}
if(/^(stats|ca|revenus?|chiffre)$/i.test(n)){const s=stats(missions);return `Pipeline actif : ${s.pipelineValue} EUR sur ${s.active} missions. Deja facture : ${s.wonValue} EUR. ${s.overdue} relance(s) en retard.`}return null}
async function openaiReply(message,history,missions,mail,session){const key=process.env.OPENAI_API_KEY;if(!key)return{configured:false,model:MODEL,source:'local',reply:`${HINT}\n\nCommandes : nouvelle mission X pour Y, relance X, termine X, bloque X, snooze X 3 jours, cherche X, digest, stats.`};const context={workspace:session.workspace,stats:stats(missions),missions:missions.slice(0,40),recentMailTasks:(mail.tasks||[]).slice(-15)};const input=[{role:'developer',content:'Tu es Jarvis pour Kroma HQ. Reponds en francais, direct, actionnable, avec une prochaine action concrete.'},...(Array.isArray(history)?history.slice(-8).map(h=>({role:h.role==='user'?'user':'assistant',content:safe(h.text,700)})):[]),{role:'user',content:`Commande: ${safe(message,1200)}\nContexte CRM:\n${JSON.stringify(context)}`}];const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:MODEL,input,max_output_tokens:520})});const p=await r.json();if(!r.ok)throw new Error(p.error?.message||'OpenAI indisponible');const text=p.output_text||(p.output||[]).flatMap(i=>i.content||[]).map(c=>c.text||'').join('\n');return{configured:true,model:MODEL,source:'openai',reply:text.trim()||'Reponse vide.'}}
function json(res,code,body){const data=JSON.stringify(body);res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Content-Length':Buffer.byteLength(data)});res.end(data)}function err(res,code,msg){json(res,code,{error:msg})}async function body(req){const c=[];for await(const x of req)c.push(x);try{return c.length?JSON.parse(Buffer.concat(c).toString('utf8')):{}}catch{return{}}}
async function apiRoute(req,res,url){const missions=await readMissions(),mm=url.pathname.match(/^\/api\/missions\/([^/]+)$/);if(req.method==='GET'&&url.pathname==='/api/missions')return json(res,200,{missions:missions.sort((a,b)=>days(a.nextActionDate)-days(b.nextActionDate)),stages:STAGES,stageLabels:LABEL});if(req.method==='GET'&&url.pathname==='/api/stats')return json(res,200,stats(missions));if(req.method==='GET'&&url.pathname==='/api/activity')return json(res,200,{activity:await readActivity()});if(req.method==='GET'&&url.pathname==='/api/session')return json(res,200,{session:await readSession()});if(req.method==='PUT'&&url.pathname==='/api/session'){const s=sanitizeSession(await body(req),await readSession());await writeSession(s);return json(res,200,{session:s})}if(req.method==='GET'&&url.pathname==='/api/jarvis/status')return json(res,200,{configured:Boolean(process.env.OPENAI_API_KEY),model:MODEL,message:process.env.OPENAI_API_KEY?'Jarvis connecte.':HINT});if(req.method==='POST'&&url.pathname==='/api/jarvis/chat'){const b=await body(req),message=safe(b.message,1600);if(!message)return err(res,400,'Commande vide.');const local=await localCommand(message,missions);if(local)return json(res,200,{configured:Boolean(process.env.OPENAI_API_KEY),model:MODEL,source:'automation',reply:local});try{return json(res,200,await openaiReply(message,b.history,missions,await readMail(),await readSession()))}catch(e){return err(res,e.status||500,e.message||'Erreur Jarvis')}}if(req.method==='POST'&&url.pathname==='/api/missions'){const m=sanitizeMission(await body(req));missions.push(m);await writeMissions(missions);await log(`Mission creee : ${m.name}`,'mission_created');return json(res,201,{mission:m})}if(mm&&req.method==='PUT'){const i=missions.findIndex(m=>m.id===mm[1]);if(i<0)return err(res,404,'Mission introuvable.');missions[i]=sanitizeMission(await body(req),missions[i]);await writeMissions(missions);return json(res,200,{mission:missions[i]})}return err(res,404,'Route API inconnue.')}
const MIME={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.png':'image/png','.json':'application/json; charset=utf-8'};
async function staticFile(req,res,pathname){let p=pathname==='/'?'/index.html':path.normalize(pathname).replace(/^(\.\.[/\\])+/,''),full=path.join(PUBLIC,p);if(!full.startsWith(PUBLIC))return err(res,403,'Interdit.');try{const d=await fs.readFile(full);res.writeHead(200,{'Content-Type':MIME[path.extname(full)]||'application/octet-stream'});res.end(d)}catch{try{const d=await fs.readFile(path.join(PUBLIC,'index.html'));res.writeHead(200,{'Content-Type':MIME['.html']});res.end(d)}catch{return err(res,404,'Introuvable.')}}}
http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host}`);if(url.pathname.startsWith('/api/'))return apiRoute(req,res,url);return staticFile(req,res,url.pathname)}catch(e){err(res,500,e.message||'Erreur serveur')}}).listen(PORT,()=>console.log(`Kroma HQ CRM sur http://localhost:${PORT}`));
